# Generated by Django 3.1.6 on 2021-06-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('c_email', models.EmailField(blank=True, default='', max_length=250, null=True)),
                ('c_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('c_address', models.TextField(default='')),
                ('c_password', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('c_regdate', models.DateField(auto_now=True, null=True)),
                ('c_profile', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='CompanyProfile/')),
            ],
        ),
    ]
