# Generated by Django 3.1.6 on 2021-06-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='c_address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='c_email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='c_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='c_num',
            new_name='company_number',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='c_password',
            new_name='company_password',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='c_profile',
            new_name='company_profile',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='c_regdate',
            new_name='company_regdate',
        ),
    ]
