# Generated by Django 3.1.6 on 2021-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210618_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company_number',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
