# Generated by Django 3.1.6 on 2021-07-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210618_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Company_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=250, null=True)),
                ('customer_number', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('customer_address1', models.TextField(default='')),
                ('customer_address2', models.TextField(default='')),
                ('customer_password', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('customer_regdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_profile', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='CustomerProfile/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company_details')),
            ],
        ),
    ]
