# Generated by Django 3.1.6 on 2021-07-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210706_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('product_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product_img', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='ProductImage/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company_details')),
            ],
        ),
    ]
