# Generated by Django 3.2.5 on 2021-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_company_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_customer',
            name='customer_number',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
    ]
